export type Course = {
  id: string;
  code: string;
  name: string;
  area: string;
  hours: string;
  modality: string;
  agenda: string;
};

export const defaultCourses: Course[] = [
  {
    id: 'course-001',
    code: 'CC-001',
    name: 'Interpretação e Auditor Interno normas ISO 37001 e ISO 37301',
    area: 'Compliance & Antissuborno',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-002',
    code: 'CC-002',
    name: 'Interpretação e Implementação da ISO/UNDP PAS 53002:2024',
    area: 'Compliance & Antissuborno',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-003',
    code: 'CC-003',
    name: 'Gestão de Riscos com base na Norma ISO 31008:2018',
    area: 'Gestão de Riscos',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-004',
    code: 'CC-004',
    name: 'Auditoria e Investigações Internas com base nas normas ISO 19011 e 37008',
    area: 'Auditoria & Investigações',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-005',
    code: 'CC-005',
    name: 'Framework Princípios ESG ISO IW48:2024',
    area: 'ESG',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-006',
    code: 'CC-006',
    name: 'Curso Avançado de ESG de Impacto Reputacional',
    area: 'ESG & Reputação',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-007',
    code: 'CC-007',
    name: 'Gestão de Risco de Fraude',
    area: 'Risco & Fraude',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-008',
    code: 'CC-008',
    name: 'Curso Executivo: Direito e Finanças Para Gestores',
    area: 'Direito & Finanças',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-009',
    code: 'CC-009',
    name: 'Curso Executivo: Governança, Risco, Compliance e Reputação Empresarial',
    area: 'Governança & Compliance',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-010',
    code: 'CC-010',
    name: 'Implementação e Gestão de Escritórios de Projectos (PMO)',
    area: 'Projectos (PMO)',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-011',
    code: 'CC-011',
    name: 'Gestão da Mudança',
    area: 'Mudança Organizacional',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-012',
    code: 'CC-012',
    name: 'Curso Global Gestão Financeira e Controlo de Gestão',
    area: 'Finanças & Controlo',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-013',
    code: 'CC-013',
    name: 'Análise de Investimento Custo-Benefício',
    area: 'Finanças & Investimentos',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-014',
    code: 'CC-014',
    name: 'Ética nas Negociações e Contratações',
    area: 'Ética & Contratações',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-015',
    code: 'CC-015',
    name: 'Gestão de Tesouraria',
    area: 'Tesouraria',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-016',
    code: 'CC-016',
    name: 'Gestão de Património',
    area: 'Património',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-017',
    code: 'CC-017',
    name: 'Segurança da Informação e Risco Cibernético',
    area: 'Segurança da Informação',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-018',
    code: 'CC-018',
    name: 'Regulamentação e Compliance no Mercado de Capitais',
    area: 'Mercado de Capitais & Compliance',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-019',
    code: 'CC-019',
    name: 'Prevenção e Combate à Procrastinação, Sedentarismo e Esgotamento Mental',
    area: 'Bem-estar & Produtividade',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-020',
    code: 'CC-020',
    name: 'Curso de Especialização em Prevenção e Combate à Corrupção, Branqueamento de Capitais e Contrabando de Produtos Petrolíferos em Angola',
    area: 'Compliance & Anticorrupção',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-021',
    code: 'CC-021',
    name: 'Green Compliance',
    area: 'Compliance Ambiental',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-022',
    code: 'CC-022',
    name: 'Compliance Officer',
    area: 'Compliance Profissional',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-023',
    code: 'CC-023',
    name: 'Governance Officer',
    area: 'Governança Profissional',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-024',
    code: 'CC-024',
    name: 'Auditoria Contabilística e Financeira',
    area: 'Auditoria & Contabilidade',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-025',
    code: 'CC-025',
    name: 'Secretariado Executivo',
    area: 'Administração',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-026',
    code: 'CC-026',
    name: 'Gestão de Tempo, Foco e Produtividade',
    area: 'Produtividade',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-027',
    code: 'CC-027',
    name: 'Liderança e Gestão de Equipas',
    area: 'Liderança',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-028',
    code: 'CC-028',
    name: 'Gestão de Carreiras e Plano de Sucessão',
    area: 'Gestão de Pessoas',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-029',
    code: 'CC-029',
    name: 'Curso Global Avançado Governança Corporativa e Compliance',
    area: 'Governança Corporativa',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-030',
    code: 'CC-030',
    name: 'Fundamentos em Gestão de Projectos',
    area: 'Projectos',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-031',
    code: 'CC-031',
    name: 'Balanced ScoreCard + OKR Master',
    area: 'Estratégia & Performance',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-032',
    code: 'CC-032',
    name: 'Gestão de Fundo Social / Caixa de Previdência',
    area: 'Previdência',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-033',
    code: 'CC-033',
    name: 'Contabilidade para Instituições Financeiras: IFRS e regulação específica',
    area: 'Contabilidade & IFRS',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
  {
    id: 'course-034',
    code: 'CC-034',
    name: 'Administração de Contas a Pagar e a Receber',
    area: 'Finanças Operacionais',
    hours: 'A definir',
    modality: 'A definir',
    agenda: 'On-demand',
  },
];
