const referenceCatalog = [
  {
    id: 'b6l',
    name: { pt: 'B6L', en: 'B6L' },
    logo: '/Nossas Referências/B6L.jpg',
    role: { pt: 'Cliente', en: 'Client' },
    comment: {
      pt: 'Implementação das normas ISO 9001, ISO 14001 e ISO 45001.',
      en: 'Implementation of ISO 9001, ISO 14001, and ISO 45001 standards.',
    },
    person: 'B6L',
    service: 'iso',
    description: {
      pt: 'Consultoria e auditoria em sistemas de gestão.',
      en: 'Consulting and auditing of management systems.',
    },
    attachments: [],
  },
  {
    id: 'esmac',
    name: { pt: 'Esmac,Lda', en: 'Esmac,Lda' },
    logo: '/Nossas Referências/Esmac.Lda.webp',
    role: { pt: 'Coordenador', en: 'Coordinator' },
    comment: { pt: 'Excelente, recomendo.', en: 'Excellent, I recommend it.' },
    person: 'Márcio Dumbo',
    service: 'iso',
    description: {
      pt: 'Consultoria e auditoria em sistemas de gestão.',
      en: 'Consulting and auditing of management systems.',
    },
    attachments: [],
  },
  {
    id: 'velonet',
    name: { pt: 'Velonet', en: 'Velonet' },
    logo: '/Nossas Referências/Velonet.png',
    role: { pt: 'Gestor de Qualidade', en: 'Quality Manager' },
    comment: {
      pt: 'Muito dedicados, comprometidos e profissionais.',
      en: 'Very dedicated, committed, and professional.',
    },
    person: 'Alves Ulo',
    service: 'iso',
    description: {
      pt: 'Consultoria e auditoria em sistemas de gestão.',
      en: 'Consulting and auditing of management systems.',
    },
    attachments: [],
  },
  {
    id: 'interseguros',
    name: {
      pt: 'InterSeguros-Corretores de Seguros, S.A.',
      en: 'InterSeguros-Corretores de Seguros, S.A.',
    },
    logo: '/Nossas Referências/Inter Seguros.png',
    role: { pt: 'Director Geral', en: 'General Director' },
    comment: {
      pt: 'Acompanhamento excelente durante e após o processo de certificação. Um parceiro que, certamente, nos acompanhará ao longo de muitos anos.',
      en: 'Excellent follow-up during and after the certification process. A partner that will certainly accompany us for many years.',
    },
    person: 'Avelina Rocha',
    service: 'iso',
    description: {
      pt: 'Consultoria e auditoria em sistemas de gestão.',
      en: 'Consulting and auditing of management systems.',
    },
    attachments: [],
  },
  {
    id: 'aclean',
    name: { pt: 'Aclean,Lda', en: 'Aclean,Lda' },
    logo: '/Nossas Referências/A Clean.jpg',
    role: { pt: 'Director Geral', en: 'General Director' },
    comment: {
      pt: 'Foi de facto muito boa a prestação, a atenção dedicada, bem como a formulação ao detalhe do sistema, o entendimento dos consultores e a maneira interativa.',
      en: 'The service was truly very good, with dedicated attention, detailed system formulation, clear understanding by the consultants, and an interactive approach.',
    },
    person: 'Gelson Salvador',
    service: 'iso',
    description: {
      pt: 'Consultoria e auditoria em sistemas de gestão.',
      en: 'Consulting and auditing of management systems.',
    },
    attachments: ['/Nossas Referências/SAQIA.png'],
  },
  {
    id: 'diway',
    name: { pt: 'Diway', en: 'Diway' },
    logo: '/Nossas Referências/Diway.jpg',
    role: { pt: 'Coordenadora da Qualidade', en: 'Quality Coordinator' },
    comment: { pt: 'Experiência agradável.', en: 'Pleasant experience.' },
    person: 'Nadiry Celestino',
    service: 'iso',
    description: {
      pt: 'Consultoria e auditoria em sistemas de gestão.',
      en: 'Consulting and auditing of management systems.',
    },
    attachments: [],
  },
  {
    id: 'imovias-urbanismo-sa',
    name: {
      pt: 'Imovias Urbanismo e Construção SA',
      en: 'Imovias Urbanismo e Construção SA',
    },
    logo: '/Nossas Referências/Imovias.png',
    role: { pt: 'PCA', en: 'Chairman of the Board' },
    comment: { pt: 'Equipa diligente.', en: 'Diligent team.' },
    person: 'Joaquim Alves',
    service: 'iso',
    description: {
      pt: 'Consultoria e auditoria em sistemas de gestão.',
      en: 'Consulting and auditing of management systems.',
    },
    attachments: [],
  },
  {
    id: 'imovias-energy',
    name: { pt: 'Imovias Energy SA', en: 'Imovias Energy SA' },
    logo: '/Nossas Referências/Imovias.png',
    role: { pt: 'PCA', en: 'Chairman of the Board' },
    comment: { pt: 'Equipa diligente.', en: 'Diligent team.' },
    person: 'Joaquim Alves',
    service: 'iso',
    description: {
      pt: 'Consultoria e auditoria em sistemas de gestão.',
      en: 'Consulting and auditing of management systems.',
    },
    attachments: [],
  },
  {
    id: 'goldproc',
    name: { pt: 'Gold Procurement', en: 'Gold Procurement' },
    logo: '/Nossas Referências/Gold Proc.jpg',
    role: { pt: 'Serviço de Procurement', en: 'Procurement Service' },
    comment: {
      pt: 'Serviço de procurement eficiente e profissional. Recomendo.',
      en: 'Efficient and professional procurement service. Recommended.',
    },
    person: 'Director de Compras',
    service: 'procurement',
    description: {
      pt: 'Serviços de procurement de materiais e equipamentos',
      en: 'Procurement services for materials and equipment',
    },
    attachments: [],
  },
  {
    id: 'bureauveritas',
    name: { pt: 'Bureau Veritas', en: 'Bureau Veritas' },
    logo: '/Nossas Referências/Bureau_Veritas-Logo.wine.png',
    role: { pt: 'Serviço de Procurement', en: 'Procurement Service' },
    comment: {
      pt: 'Excelente parceria em serviços de procurement. Qualidade garantida.',
      en: 'Excellent partnership in procurement services. Quality guaranteed.',
    },
    person: 'Director de Operações',
    service: 'procurement',
    description: {
      pt: 'Serviços de procurement e consultoria',
      en: 'Procurement and consultancy services',
    },
    attachments: [],
  },
  {
    id: 'petromar',
    name: { pt: 'Petromar', en: 'Petromar' },
    logo: '/Nossas Referências/PetroMar.jpg',
    role: { pt: 'Serviço de Procurement', en: 'Procurement Service' },
    comment: {
      pt: 'Serviço de procurement de excelência. A ILUNGI entregou com qualidade.',
      en: 'Excellent procurement service. ILUNGI delivered with quality.',
    },
    person: 'Director de Compras',
    service: 'procurement',
    description: {
      pt: 'Serviços de procurement para indústria petrolífera',
      en: 'Procurement services for oil industry',
    },
    attachments: [],
  },
  {
    id: 'pensana',
    name: { pt: 'Pensana', en: 'Pensana' },
    logo: '/Nossas Referências/pensana-logo-sticky-blue-standard.png',
    role: {
      pt: 'Serviço de Assistência e Suporte de TI',
      en: 'IT Assistance and Support Service',
    },
    comment: {
      pt: 'Tivemos uma ótima experiência trabalhando com a ILUNGI na nossa migração e configuração do ERP. A equipa foi profissional, experiente e fez com que um processo que poderia ser muito complexo fosse tranquilo e gerível.\n\nEles nos apoiaram na migração, validação e reconciliação de dados, além de ajudar na configuração de módulos-chave, incluindo contabilidade, tesouraria/bancos, fornecedores, IVA e ativos fixos. A atenção ao detalhe garantiu que nossos dados estivessem corretos, alinhados e prontos para as operações diárias desde o início.\n\nEstavam sempre dispostos a ir além para apoiar nossa equipa, seja resolvendo problemas, respondendo perguntas ou ajudando-nos a sentir-nos confortáveis com o sistema. A sua capacidade de resposta e abordagem prática realmente se destacaram.\n\nEstamos muito satisfeitos com o resultado e os recomendaríamos com prazer.\n\nAtenciosamente,\n\nAngie Bles (de Oliveira)\n\nFinancial Manager Angola/Portugal',
      en: 'We had a great experience working with ILUNGI on our ERP migration and configuration. The team was professional, experienced, and made what could have been a very complex process smooth and manageable.\n\nThey supported us in the migration, validation, and reconciliation of data, as well as helping with the configuration of key modules including accounting, treasury/banks, suppliers, VAT, and fixed assets. The attention to detail ensured our data was correct, aligned, and ready for daily operations from the start.\n\nThey were always willing to go above and beyond to support our team, whether resolving issues, answering questions, or helping us feel comfortable with the system. Their responsiveness and practical approach really stood out.\n\nWe are very satisfied with the result and would gladly recommend them.\n\nSincerely,\n\nAngie Bles (de Oliveira)\n\nFinancial Manager Angola/Portugal',
    },
    person: 'Angie Bles (de Oliveira)',
    service: 'pmo',
    description: {
      pt: 'Migração e configuração do ERP Cegid Primavera para Ozango Minerais S.A.',
      en: 'Cegid Primavera ERP migration and configuration for Ozango Minerais S.A.',
    },
    attachments: [],
  },
  {
    id: 'bioprev',
    name: { pt: 'BioPrev', en: 'BioPrev' },
    logo: '/Nossas Referências/BioPrev.webp',
    role: {
      pt: 'Serviço de Assistência e Suporte de TI',
      en: 'IT Assistance and Support Service',
    },
    comment: {
      pt: 'A ILUNGI garantiu estabilidade e melhoria dos nossos sistemas de TI.',
      en: 'ILUNGI ensured stability and improvements in our IT systems.',
    },
    person: 'Director de Tecnologia',
    service: 'pmo',
    description: {
      pt: 'Implementação do Primavera e suporte de TI',
      en: 'Primavera implementation and IT support',
    },
    attachments: [],
  },
];

module.exports = referenceCatalog;
