const referenceCatalog = [
  {
    id: 'aclean',
    name: { pt: 'Aclean,Lda', en: 'Aclean,Lda' },
    logo: '/Nossas Refer\u00eancias/A Clean.jpg',
    role: { pt: 'Director Geral', en: 'General Director' },
    comment: {
      pt: 'Foi de facto muito boa a presta\u00e7\u00e3o, a aten\u00e7\u00e3o dedicada, bem como a formula\u00e7\u00e3o ao detalhe do sistema, o entendimento dos consultores e a maneira interativa.',
      en: "The service was indeed very good, as was the dedicated attention, the detailed formulation of the system, the consultants' understanding, and the interactive approach.",
    },
    person: 'Gelson Salvador',
    service: 'iso',
    description: {
      pt: 'Consultoria e auditoria em sistemas de gest\u00e3o.',
      en: 'Consulting and auditing of management systems.',
    },
    attachments: ['/Nossas Refer\u00eancias/SAQIA.png'],
  },
  {
    id: 'aguia-do-sul',
    name: { pt: 'Aguia do Sul', en: 'Aguia do Sul' },
    logo: '/Nossas Refer\u00eancias/Aguias do Sul.png',
    role: { pt: 'CEO - Aguia do Sul', en: 'CEO - Aguia do Sul' },
    comment: {
      pt: 'Temos orgulho em recomendar a Ilungi pelo excelente trabalho de consultoria prestado durante o nosso processo de implementa\u00e7\u00e3o ISO.\nCom profissionalismo, dedica\u00e7\u00e3o e acompanhamento pr\u00f3ximo, a Ilungi foi fundamental para que alcan\u00e7\u00e1ssemos as certifica\u00e7\u00f5es ISO 9001, 14001 e 45001 com sucesso.\nAgradecemos pela parceria, compet\u00eancia t\u00e9cnica e compromisso com a excel\u00eancia demonstrados em cada etapa deste importante marco para a nossa empresa.',
      en: 'We are proud to recommend ILUNGI for the excellent consulting work provided during our ISO implementation process.\nWith professionalism, dedication, and close follow-up, ILUNGI was fundamental for us to successfully achieve ISO 9001, 14001, and 45001 certifications.\nWe are grateful for the partnership, technical competence, and commitment to excellence demonstrated at each stage of this important milestone for our company.',
    },
    person: 'Evelin M S Santos',
    service: 'iso',
    description: {
      pt: 'Consultoria e auditoria em sistemas de gest\u00e3o.',
      en: 'Consulting and auditing of management systems.',
    },
    attachments: [],
  },
  {
    id: 'b6l',
    name: { pt: 'B6L', en: 'B6L' },
    logo: '/Nossas Refer\u00eancias/B6L.jpg',
    role: { pt: 'Diretor Geral', en: 'General Director' },
    comment: {
      pt: 'Somos gratos por mais este passo rumo aos nossos objetivos. \u00c0 ILUNGI, agradecemos n\u00e3o apenas pela parceria, mas pelo suporte e orienta\u00e7\u00e3o fundamentais para o nosso crescimento. A satisfa\u00e7\u00e3o de seus parceiros \u00e9 reflexo de compromisso e disciplina. Vamos juntos, pois a grandiosidade se alcan\u00e7a em conjunto.',
      en: 'We are grateful for this further step toward our goals. To ILUNGI, we are grateful not only for the partnership, but for the support and guidance that were fundamental to our growth. The satisfaction of your partners reflects commitment and discipline. Let us move forward together, because greatness is achieved collectively.',
    },
    person: 'Benetti Bumba',
    service: 'iso',
    description: {
      pt: 'Consultoria e auditoria em sistemas de gest\u00e3o.',
      en: 'Consulting and auditing of management systems.',
    },
    attachments: [],
  },
  {
    id: 'bioprev',
    name: { pt: 'BioPrev', en: 'BioPrev' },
    logo: '/Nossas Refer\u00eancias/BioPrev.webp',
    role: {
      pt: 'Servi\u00e7o de Assist\u00eancia e Suporte de TI',
      en: 'IT Assistance and Support Service',
    },
    comment: {
      pt: 'A ILUNGI garantiu estabilidade e melhoria dos nossos sistemas de TI.',
      en: 'ILUNGI ensured stability and improvement in our IT systems.',
    },
    person: 'Director de Tecnologia',
    service: 'pmo',
    description: {
      pt: 'Implementa\u00e7\u00e3o do Primavera e suporte de TI',
      en: 'Primavera implementation and IT support',
    },
    attachments: [],
  },
  {
    id: 'bureauveritas',
    name: { pt: 'Bureau Veritas', en: 'Bureau Veritas' },
    logo: '/Nossas Refer\u00eancias/Bureau_Veritas-Logo.wine.png',
    role: { pt: 'Servi\u00e7o de Procurement', en: 'Procurement Service' },
    comment: {
      pt: 'Excelente parceria em servi\u00e7os de procurement. Qualidade garantida.',
      en: 'Excellent partnership in procurement services. Quality guaranteed.',
    },
    person: 'Director de Opera\u00e7\u00f5es',
    service: 'procurement',
    description: {
      pt: 'Servi\u00e7os de procurement e consultoria',
      en: 'Procurement and consultancy services',
    },
    attachments: [],
  },
  {
    id: 'diway',
    name: { pt: 'Diway', en: 'Diway' },
    logo: '/Nossas Refer\u00eancias/Diway.jpg',
    role: { pt: 'Coordenadora da Qualidade', en: 'Quality Coordinator' },
    comment: { pt: 'Experi\u00eancia agrad\u00e1vel.', en: 'Pleasant experience.' },
    person: 'Nadiry Celestino',
    service: 'iso',
    description: {
      pt: 'Consultoria e auditoria em sistemas de gest\u00e3o.',
      en: 'Consulting and auditing of management systems.',
    },
    attachments: [],
  },
  {
    id: 'esmac',
    name: { pt: 'Esmac,Lda', en: 'Esmac,Lda' },
    logo: '/Nossas Refer\u00eancias/Esmac.Lda.webp',
    role: { pt: 'Coordenador', en: 'Coordinator' },
    comment: { pt: 'Excelente, recomendo.', en: 'Excellent, I recommend it.' },
    person: 'M\u00e1rcio Dumbo',
    service: 'iso',
    description: {
      pt: 'Consultoria e auditoria em sistemas de gest\u00e3o.',
      en: 'Consulting and auditing of management systems.',
    },
    attachments: [],
  },
  {
    id: 'goldproc',
    name: { pt: 'Gold Procurement', en: 'Gold Procurement' },
    logo: '/Nossas Refer\u00eancias/Gold Proc.jpg',
    role: { pt: 'Servi\u00e7o de Procurement', en: 'Procurement Service' },
    comment: {
      pt: 'Servi\u00e7o de procurement eficiente e profissional. Recomendo.',
      en: 'Efficient and professional procurement service. I recommend it.',
    },
    person: 'Director de Compras',
    service: 'procurement',
    description: {
      pt: 'Servi\u00e7os de procurement de materiais e equipamentos',
      en: 'Procurement services for materials and equipment',
    },
    attachments: [],
  },
  {
    id: 'imovias-energy',
    name: { pt: 'Imovias Energy SA', en: 'Imovias Energy SA' },
    logo: '/Nossas Refer\u00eancias/Imovias.png',
    role: { pt: 'PCA', en: 'Chairman of the Board' },
    comment: { pt: 'Equipa diligente.', en: 'Diligent team.' },
    person: 'Joaquim Alves',
    service: 'iso',
    description: {
      pt: 'Consultoria e auditoria em sistemas de gest\u00e3o.',
      en: 'Consulting and auditing of management systems.',
    },
    attachments: [],
  },
  {
    id: 'imovias-urbanismo-sa',
    name: {
      pt: 'Imovias Urbanismo e Constru\u00e7\u00e3o SA',
      en: 'Imovias Urbanismo e Constru\u00e7\u00e3o SA',
    },
    logo: '/Nossas Refer\u00eancias/Imovias.png',
    role: {
      pt: 'Directora Administrativa e RH',
      en: 'Administrative and HR Director',
    },
    comment: {
      pt: 'Foi um processo muito bem planeado.',
      en: 'It was a very well-planned process.',
    },
    person: 'Paula Carneiro',
    service: 'iso',
    description: {
      pt: 'Consultoria e auditoria em sistemas de gest\u00e3o.',
      en: 'Consulting and auditing of management systems.',
    },
    attachments: [],
  },
  {
    id: 'interseguros',
    name: {
      pt: 'InterSeguros-Corretores de Seguros, S.A.',
      en: 'InterSeguros-Corretores de Seguros, S.A.',
    },
    logo: '/Nossas Refer\u00eancias/Inter Seguros.png',
    role: { pt: 'Director Geral', en: 'General Director' },
    comment: {
      pt: 'Acompanhamento excelente durante e ap\u00f3s o processo de certifica\u00e7\u00e3o. Um parceiro que, certamente, nos acompanhar\u00e1 ao longo de muitos anos.',
      en: 'Excellent follow-up during and after the certification process. A partner that will certainly accompany us for many years.',
    },
    person: 'Avelina Rocha',
    service: 'iso',
    description: {
      pt: 'Consultoria e auditoria em sistemas de gest\u00e3o.',
      en: 'Consulting and auditing of management systems.',
    },
    attachments: [],
  },
  {
    id: 'pensana',
    name: { pt: 'Pensana', en: 'Pensana' },
    logo: '/Nossas Refer\u00eancias/pensana-logo-sticky-blue-standard.png',
    role: {
      pt: 'Servi\u00e7o de Assist\u00eancia e Suporte de TI',
      en: 'IT Assistance and Support Service',
    },
    comment: {
      pt: 'Tivemos uma \u00f3tima experi\u00eancia trabalhando com a ILUNGI na nossa migra\u00e7\u00e3o e configura\u00e7\u00e3o do ERP. A equipa foi profissional, experiente e fez com que um processo que poderia ser muito complexo fosse tranquilo e ger\u00edvel.\n\nEles nos apoiaram na migra\u00e7\u00e3o, valida\u00e7\u00e3o e reconcilia\u00e7\u00e3o de dados, al\u00e9m de ajudar na configura\u00e7\u00e3o de m\u00f3dulos-chave, incluindo contabilidade, tesouraria/bancos, fornecedores, IVA e ativos fixos. A aten\u00e7\u00e3o ao detalhe garantiu que nossos dados estivessem corretos, alinhados e prontos para as opera\u00e7\u00f5es di\u00e1rias desde o in\u00edcio.\n\nEstavam sempre dispostos a ir al\u00e9m para apoiar nossa equipa, seja resolvendo problemas, respondendo perguntas ou ajudando-nos a sentir-nos confort\u00e1veis com o sistema. A sua capacidade de resposta e abordagem pr\u00e1tica realmente se destacaram.\n\nEstamos muito satisfeitos com o resultado e os recomendar\u00edamos com prazer.\n\nAtenciosamente,\n\nAngie Bles (de Oliveira)\n\nFinancial Manager Angola/Portugal',
      en: 'We had a great experience working with ILUNGI on our ERP migration and configuration. The team was professional, experienced, and made a process that could have been very complex smooth and manageable.\n\nThey supported us in the migration, validation, and reconciliation of data, as well as helping with the configuration of key modules, including accounting, treasury/banks, suppliers, VAT, and fixed assets. The attention to detail ensured that our data was correct, aligned, and ready for daily operations from the start.\n\nThey were always willing to go above and beyond to support our team, whether by resolving problems, answering questions, or helping us feel comfortable with the system. Their responsiveness and practical approach really stood out.\n\nWe are very satisfied with the result and would gladly recommend them.\n\nSincerely,\n\nAngie Bles (de Oliveira)\n\nFinancial Manager Angola/Portugal',
    },
    person: 'Angie Bles (de Oliveira)',
    service: 'pmo',
    description: {
      pt: 'Migra\u00e7\u00e3o e configura\u00e7\u00e3o do ERP Cegid Primavera para Ozango Minerais S.A.',
      en: 'Cegid Primavera ERP migration and configuration for Ozango Minerais S.A.',
    },
    attachments: [],
  },
  {
    id: 'petromar',
    name: { pt: 'Petromar', en: 'Petromar' },
    logo: '/Nossas Refer\u00eancias/PetroMar.jpg',
    role: { pt: 'Servi\u00e7o de Procurement', en: 'Procurement Service' },
    comment: {
      pt: 'Servi\u00e7o de procurement de excel\u00eancia. A ILUNGI entregou com qualidade.',
      en: 'Procurement service of excellence. ILUNGI delivered with quality.',
    },
    person: 'Director de Compras',
    service: 'procurement',
    description: {
      pt: 'Servi\u00e7os de procurement para ind\u00fastria petrol\u00edfera',
      en: 'Procurement services for the oil industry',
    },
    attachments: [],
  },
  {
    id: 'apriori',
    name: { pt: 'Aprori Consultoria e Formações', en: 'Aprori Consultoria e Formações' },
    logo: '/Nossas Refer\u00eancias/APRORI.jpeg',
    role: { pt: 'Consultor', en: 'Consultant' },
    comment: {
      pt: 'Recebi um apoio exemplar durante todo o processo de obten\u00e7\u00e3o da ISO. A equipa mostrou compet\u00eancia, disponibilidade e orienta\u00e7\u00e3o clara em cada etapa. Fiquei extremamente satisfeito com o acompanhamento e recomendo o trabalho.',
      en: 'I received exemplary support throughout the entire ISO certification process. The team demonstrated competence, availability, and clear guidance at every step. I was extremely satisfied with the follow-up and recommend the work.',
    },
    person: 'Carlos Araujo',
    service: 'iso',
    description: {
      pt: 'Consultoria e auditoria em sistemas de gest\u00e3o.',
      en: 'Consulting and auditing of management systems.',
    },
    attachments: [],
  },
  {
    id: 'velonet',
    name: { pt: 'Velonet', en: 'Velonet' },
    logo: '/Nossas Refer\u00eancias/Velonet.png',
    role: { pt: 'Gestor de Qualidade', en: 'Quality Manager' },
    comment: {
      pt: 'Muito dedicados, comprometidos e profissionais.',
      en: 'Very dedicated, committed, and professional.',
    },
    person: 'Alves Ulo',
    service: 'iso',
    description: {
      pt: 'Consultoria e auditoria em sistemas de gest\u00e3o.',
      en: 'Consulting and auditing of management systems.',
    },
    attachments: [],
  },
];

module.exports = referenceCatalog;
